name: ruby-master

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_tool: [ "rubygems", "bundler" ]
    container:
      image: rubylang/ruby:master-nightly-bionic
      env:
        TEST_TOOL: ${{ matrix.test_tool }}
    steps:
      - name: Setup Requirements
        run: |
          apt update -qy
          apt install zip -qy
          gem install rake --no-document
      - uses: actions/checkout@master
      - run: git submodule update -i
      - name: ruby -v
        run: ruby -v
      - name: Install Dependencies
        run: util/ci.sh before_script
      - name: Run Test
        run: util/ci.sh script
