name: ubuntu-rvm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ 'ruby-head', 'jruby-9.2.8.0' ]
        test_tool: [ "rubygems", "bundler" ]
        exclude:
          - ruby: ruby-head
            test_tool: rubygems
          - ruby: jruby-9.2.8.0
            test_tool: bundler
    steps:
    - name: Setup Requirements
      run: |
        sudo apt update -qy
        sudo apt install groff-base graphviz -qy
    - uses: actions/checkout@master
    - run: git submodule update -i
    - name: Fixed world writable dirs
      run: |
        chmod go-w $HOME
        sudo chmod -R go-w /usr/share
        sudo chmod -R go-w /opt
    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash
    - name: Set up Ruby
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install ${{ matrix.ruby }} --binary
        rvm --default use ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        source $HOME/.rvm/scripts/rvm
        util/ci.sh before_script
      env:
        TEST_TOOL: ${{ matrix.test_tool }}
    - name: Run test
      run: |
        source $HOME/.rvm/scripts/rvm
        util/ci.sh script
      continue-on-error: true
      env:
        TEST_TOOL: ${{ matrix.test_tool }}
